///
/// ********************************************************
///
/// Auto generated by `merry flutter mobx`
///
/// ********************************************************
/// 

{{#each definitions}}
{{#this}}
{{#if responses}}

/// {{summary}}
{{{responses}}}
{{/if}}

{{#if parameters}}

/// {{summary}}
{{{parameters}}}
{{/if}}


{{/this}}
{{/each}}
